
use [raw_call_master]

DROP TABLE  IF EXISTS TicketResolution;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Feedback;
