:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_category.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_customer.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_date.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_department.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_description.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_employee.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_feedback.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_junk.sql
:r C:\\Users\\Marcel\\Documents\\Studia\\data_warehouse\\Schemas\\DataWarehouse_git_rep_now\\SqlQuery\\ETL\\ETL_load_TicketResolution.sql
